name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        
    - name: Restore dependencies
      run: dotnet restore CalculatorDemo/CalculatorDemo.csproj
      
    - name: Build Release
      run: dotnet build CalculatorDemo/CalculatorDemo.csproj --no-restore --configuration Release
      
    - name: Run tests
      run: dotnet test CalculatorDemo/CalculatorDemo.csproj --no-build --configuration Release
      
    - name: Publish
      run: dotnet publish CalculatorDemo/CalculatorDemo.csproj --configuration Release --output ./publish --self-contained true --runtime win-x64
      
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v2
      with:
        files: |
          ./publish/**/*
        draft: false
        prerelease: false
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: calculator-demo-build
        path: ./publish/
        retention-days: 30 